version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: "out"

  cache:
    paths:
      - "node_modules/**/*"